language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
env:
  - DJANGO="Django>2.0,<3.1"
  - DJANGO="Django>2.0,<3.1"
  - DJANGO="Django>2.0,<3.1"
  - DJANGO="Django>2.0,<3.1"
  - DJANGO="Django>2.0,<3.1"

before_install:
  - PWD=`pwd`
  - echo '## Installing wkhtmltopdf dependencies'
  - sudo apt-get update -qq
  - sudo apt-get install -y libxrender1 libfontconfig1 zlib1g libfreetype6 libx11-6 libxext6
  - echo '## Installing wkhtmltopdf'
  - wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz
  - tar xf wkhtmltox-0.12.4_linux-generic-amd64.tar.xz
  - export WKHTMLTOPDF_CMD="$PWD/wkhtmltox/bin/wkhtmltopdf"
install:
  - pip install $DJANGO
  - pip install -r test_requirements.txt
  - pip install .
script:
  - make test
notifications:
  email: false
